package greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.Accounts;
import greendao.Cookies;

import greendao.AccountsDao;
import greendao.CookiesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig accountsDaoConfig;
    private final DaoConfig cookiesDaoConfig;

    private final AccountsDao accountsDao;
    private final CookiesDao cookiesDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        accountsDaoConfig = daoConfigMap.get(AccountsDao.class).clone();
        accountsDaoConfig.initIdentityScope(type);

        cookiesDaoConfig = daoConfigMap.get(CookiesDao.class).clone();
        cookiesDaoConfig.initIdentityScope(type);

        accountsDao = new AccountsDao(accountsDaoConfig, this);
        cookiesDao = new CookiesDao(cookiesDaoConfig, this);

        registerDao(Accounts.class, accountsDao);
        registerDao(Cookies.class, cookiesDao);
    }
    
    public void clear() {
        accountsDaoConfig.getIdentityScope().clear();
        cookiesDaoConfig.getIdentityScope().clear();
    }

    public AccountsDao getAccountsDao() {
        return accountsDao;
    }

    public CookiesDao getCookiesDao() {
        return cookiesDao;
    }

}
